const RequiredValidator = require('./RequiredValidator')

describe('RequiredValidator', () => {
  it('should be defined', () => {
    expect(typeof RequiredValidator).toBe('function')
  })
  it('validate (empty not allowed) should return errors on missing attributes', () => {
    const validator = new RequiredValidator()
    expect(validator.validate('a', {})).toHaveLength(1)
    expect(validator.validate('a', { a: undefined })).toHaveLength(1)
    expect(validator.validate('a', { a: null })).toHaveLength(1)
    expect(validator.validate('a', { a: '' })).toHaveLength(1)
    expect(validator.validate('a', { a: 't' })).toHaveLength(0)
    expect(validator.validate('a', { a: 0 })).toHaveLength(0)
    expect(validator.validate('a', { a: 1 })).toHaveLength(0)
    expect(validator.validate('a', { a: true })).toHaveLength(0)
    expect(validator.validate('a', { a: false })).toHaveLength(0)
  })
  it('validate (empty allowed) should return errors on missing attributes', () => {
    const validator = new RequiredValidator(true)
    expect(validator.validate('a', {})).toHaveLength(1)
    expect(validator.validate('a', { a: undefined })).toHaveLength(1)
    expect(validator.validate('a', { a: null })).toHaveLength(1)
    expect(validator.validate('a', { a: '' })).toHaveLength(0)
    expect(validator.validate('a', { a: 't' })).toHaveLength(0)
    expect(validator.validate('a', { a: 0 })).toHaveLength(0)
    expect(validator.validate('a', { a: 1 })).toHaveLength(0)
    expect(validator.validate('a', { a: true })).toHaveLength(0)
    expect(validator.validate('a', { a: false })).toHaveLength(0)
  })
})
